Feat: Added at_chat_flutter sample to trunk
atsign-foundation/at_app_cli pull request #159
Opened 2022-06-29 17:45 UTC by CemTitor

**- What I did**

- Added sample from at_widgets repository
  - at_chat_flutter 
- Added json-schemas for brick.yaml and pubspec.yaml to make template maintenance easier

**- How I did it**

- Copied the lib folder from at_widgets repository, wrote the necessary config files
- Built and bundled at_app
 
**- How to verify it**
1. Pull this branch
2. List the samples with `dart run at_app/bin/at_app.dart create --list-samples`
3. Run `dart run at_app/bin/at_app.dart create -s at_chat_flutter <path/to/output>` 
4. Run generated sample app and verify that it work

**- Description for the changelog**
Added at_chat_flutter sample

2022-06-29 22:39 UTC, XavierChanth requested changes

2022-06-29 22:39 UTC, xavierchanth commented on templates/samples/at_chat_flutter/pubspec.yaml
> +  at_chat_flutter:
Please double check version numbers:
at_app_flutter should be ^5.0.0, and at_chat_flutter ^3.0.6

2022-06-30 11:04 UTC, CemTitor commented on templates/samples/at_chat_flutter/pubspec.yaml
> +  at_chat_flutter:
Sorry for that, I am updating now

2022-06-30 14:26 UTC, xavierchanth approved these changes

2022-06-30 16:28 UTC, merged