feat: Added five sample apps to trunk
atsign-foundation/at_app_cli pull request #167
Opened 2022-07-05 15:57 UTC by CemTitor

samples:

- [x] at_invitation_flutter
- [x] at_location_flutter
- [x] at_notify_flutter
- [x] at_sync_ui_flutter
- [x] at_theme_flutter

**- What I did**

- Added sample from at_widgets repository
  - Added at_invitation_flutter
  - Added at_location_flutter
  - Added at_notify_flutter
  - Added at_sync_ui_flutter
  - Added at_theme_flutter
- Added json-schemas for brick.yaml and pubspec.yaml to make template maintenance easier

**- How I did it**

- Copied the lib folder from each example, wrote the necessary config files for each template
- Built and bundled at_app
 
**- How to verify it**
1. Pull this branch
2. List the samples with `dart run at_app/bin/at_app.dart create --list-samples`
3. Run `dart run at_app/bin/at_app.dart create -s <sample> <path/to/output>` for each sample
4. Run each generated sample app and verify that they work

**- Description for the changelog**
Added at_invitation_flutter, at_location_flutter, at_notify_flutter, at_sync_ui_flutter, at_theme_flutter samples to trunk

2022-07-05 20:44 UTC, XavierChanth requested changes
For now, maybe change the url to atsign.dev/samples/at_invitation_flutter

2022-07-05 20:44 UTC, XavierChanth commented on templates/samples/at_invitation_flutter/__brick__/lib/constants.dart
> +  static const String cookiePage = 'https://3e2a-122-167-192-153.ngrok.io';
We will need to host a webpage and update the url for it.

2022-07-06 10:21 UTC, CemTitor commented on templates/samples/at_invitation_flutter/__brick__/lib/constants.dart
> +  static const String cookiePage = 'https://3e2a-122-167-192-153.ngrok.io';
I changed url to atsign.dev/samples/at_invitation_flutter

2022-07-20 17:11 UTC, XavierChanth approved these changes

2022-07-20 17:13 UTC, merged