Change the linter to flutter_lints
atsign-foundation/at_app_cli pull request #27
Opened 2021-10-11 10:11 UTC by prasadsunny1

Fixes #24 

**- What I did**
Change the linter package from pedantic to flutter_lints

**- How I did it**
Change the dependency

**- How to verify it**
Inspect the file `pubspec.yaml`

2021-10-11 10:17 UTC, cpswan commented on pubspec.lock
>    pedantic:
I'm not sure there should even be a pedantic section here any more, which is why I've asked @XavierChanth to review.

There may also be a need for an analysis-options.yaml

2021-10-11 10:31 UTC, prasadsunny1 commented on pubspec.lock
>    pedantic:
Will add that

2021-10-12 04:19 UTC, prasadsunny1 commented on pubspec.lock
>    pedantic:
Done, I have added analysis options and some refactorings that it suggested.

2021-10-12 04:21 UTC, prasadsunny1 commented
Added analysis_option.yaml
Resolved some items suggested by flutter_lints
Refreshed pubspec.lock file

2021-10-12 13:33 UTC, xavierchanth requested changes
Thank you for you PR, there are a few changes I am requesting:

- The log statements should use the custom logger
- No flutter in this project so please use package:lints instead

2021-10-12 13:33 UTC, xavierchanth commented on lib/src/command_runner.dart
> +      log('at_app ${packageVersion.toString()}');
Good catch, this should use the existing logger in the class though:
```
_logger.i('...');
```

2021-10-12 13:33 UTC, xavierchanth commented on analysis_options.yaml
> +include: package:flutter_lints/flutter.yaml
This is a dart project, it should use the [dart lint options](https://pub.dev/packages/lints).

2021-10-12 13:33 UTC, xavierchanth commented on lib/src/util/cli/flutter.dart
> +    if (androidLanguage != null) {
I used shorthand in these lines for readability, please try to keep the formatting the same.

2021-11-16 17:08 UTC, merged